<a href="https://colab.research.google.com/github/sleepycloudy/pytorch-tutorial-youtube/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor math operations
*   Add,Subtract,Multiple,Divide,Remainders,Exponents
*   Shorthand and Longhand
*   Reassignment

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# Multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# Mul longhanded
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Div longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Remainder Modulus
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponent / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

tensor_a的值做底数，tensor_b的值做root

In [ ]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([1, 2, 3, 4])

In [ ]:
# tensor_a =  tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

tensor1.add_(tensor1) add_ 会改变tensor1的值
没有下划线的话，不会修改tensor的值

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([11, 14, 17, 20])